const accidentsCollection = "nesrece",
	peopleCollection = "osebe";

module.exports = {
	graph23: {
		id: 23,
		title: "Nesreče glede na leto",
		values: ["2014", "2015", "2016", "2017", "2018"],
		decodedValues: [],
		keys: ["leto", "nesrece"],
		collection: accidentsCollection,
		attribute: "Datum_Nesrece",
		regex: true
	},
	graph24: {
		id: 24,
		title: "Nesreče glede na dan",
		values: ["0w", "1w", "2w", "3w", "4w", "5w", "6w"],
		decodedValues: [
			"ponedeljek",
			"torek",
			"sreda",
			"četrtek",
			"petek",
			"sobota",
			"nedelja"
		],
		keys: ["dan", "nesrece"],
		collection: accidentsCollection,
		attribute: "dan_v_tednu",
		regex: false
	},
	graph25: {
		id: 25,
		title: "Nesreče glede na vreme",
		values: ["J", "O", "D", "N", "M", "S", "V", "T"],
		decodedValues: [
			"JASNO",
			"OBLAČNO",
			"DEŽEVNO",
			"NEZNANO",
			"MEGLA",
			"SNEG",
			"VETER",
			"TOČA"
		],
		keys: ["vreme", "nesrece"],
		collection: accidentsCollection,
		attribute: "PRVR_Vreme",
		regex: false
	},
	graph26: {
		id: 26,
		title: "Nesreče glede na vzroke",
		values: ["NP", "SV", "PV", "OS", "HI", "PD", "PR", "VR", "TO", "CE", "VO"],
		decodedValues: [
			"Nepravilnost pešca",
			"Nepravilna smer vožnje",
			"Premiki z vozilom",
			"Ostalo",
			"Neprilagojena Hitrost",
			"Neupoštevanje pravil o prednosti",
			"Nepravilno prehitevanje",
			"Neustrezna varnostna razdalja",
			"Nepravilnost na tovoru",
			"Nepravilnost na cesti",
			"Neustrezna varnostna razdalja"
		],
		keys: ["vzrok", "nesrece"],
		collection: accidentsCollection,
		attribute: "PRVZ_vzrok",
		regex: false
	},
	graph27: {
		id: 27,
		title: "Nesreče glede na vozilo",
		values: [7, 11, 5, 12, 8, 10, 2, 4, 9, 3, 6, 1],
		decodedValues: [
			"tovorno vozilo",
			"delovno vozilo",
			"avtobus",
			"tovorno vozilo",
			"tovorno vozilo",
			"vlečno vozilo",
			"osebni avtomobil",
			"avtobus",
			"tovorno vozilo",
			"avtobus",
			"avtobus",
			"osebni avtomobil"
		],
		keys: ["vozilo", "nesrece"],
		collection: accidentsCollection,
		attribute: "LVVN_vrsta_vozila",
		regex: true
	},
	graph28: {
		id: 28,
		title: "Nesreče glede na udelezence",
		values: [
			"AV",
			"DS",
			"K1",
			"KM",
			"KO",
			"KR",
			"KV",
			"LK",
			"LV",
			"M1",
			"MK",
			"MO",
			"OA",
			"OD",
			"OS",
			"PE",
			"PO",
			"PT",
			"SD",
			"SK",
			"SM",
			"SP",
			"SV",
			"TK",
			"TR",
			"TV",
			"UC",
			"KO",
			"MK",
			"OA",
			"PE",
			"PT",
			"XX"
		],
		decodedValues: [
			"VOZNIK AVTOBUSA",
			"VOZNIK DELOVNEGA STROJA",
			"VOZNIK KOLESA S POMOŽNIM ELEKTRIČNIM MOTORJEM",
			"VOZNIK KOLESA Z MOTORJEM",
			"KOLESAR",
			"X-KRŠITELJ - JRM",
			"VOZNIK KOMBINIRANEGA VOZILA",
			"VOZNIK LAHKEGA ŠTIRIKOLESA",
			"LASTNIK VOZILA",
			"VOZNIK MOPEDA DO 25 KM/H",
			"VOZNIK MOTORNEGA KOLESA",
			"VOZNIK MOPEDA",
			"VOZNIK OSEBNEGA AVTOMOBILA",
			"ODGOVORNA OSEBA",
			"OSTALO",
			"PEŠEC",
			"PRAVNA OSEBA",
			"POTNIK",
			"POSAMEZNIK, S.P., KI SAMOSTOJNO OPRAVLJA DEJAVNOST IN ZAPOSLUJE DRUGE",
			"VOZNIK ŠTIRIKOLESA",
			"SKRBNIK MLADOLETNIKA",
			"SAMOSTOJNI PODJETNIK",
			"VOZNIK SPECIALNEGA VOZILA",
			"VOZNIK TRIKOLESA",
			"VOZNIK TRAKTORJA",
			"VOZNIK TOVORNEGA VOZILA",
			"UČITELJ VOŽNJE MED USPOSABLJANJEM KANDIDATA ZA VOZNIKA MV",
			"KOLESARJI",
			"VOZNIKI MOTORNIH KOLES",
			"VOZNIKI OSEBNIH AVTOMOBILOV",
			"PEŠCI",
			"POTNIKI",
			"DRUGI UDELEŽENCI"
		],
		keys: ["udelezenec", "nesrece"],
		collection: peopleCollection,
		attribute: "PRVO_vloga_udelezenca",
		regex: false
	},
	graph29: {
		id: 29,
		title: "Nesreče glede na praznik",
		values: [true, false],
		decodedValues: ["Praznik", "Delovnik"],
		keys: ["dan", "nesrece"],
		collection: accidentsCollection,
		attribute: "je_praznik",
		regex: false
	},
	graph30: {
		id: 30,
		title: "Nesreče glede na tip",
		values: ["BT", "ČT", "NT", "OP", "OS", "PP", "PR", "PZ", "TO", "TV"],
		decodedValues: [
			"BOČNO TRČENJE",
			"ČELNO TRČENJE",
			"NALETNO TRČENJE",
			"OPLAŽENJE",
			"OSTALO",
			"POVOŽENJE PEŠCA",
			"PREVRNITEV VOZILA",
			"POVOŽENJE ŽIVALI",
			"TRČENJE V OBJEKT",
			"TRČENJE V STOJEČE / PARKIRANO VOZILO"
		],
		keys: ["tip", "nesrece"],
		collection: accidentsCollection,
		attribute: "PRPV_Tip_Nesrece",
		regex: false
	},
	graph31: {
		id: 31,
		title: "Nesreče glede na stanje prometa",
		values: ["E", "G", "N", "R", "Z"],
		decodedValues: ["NEZNANO", "GOST", "NORMALEN", "REDEK", "ZASTOJI"],
		keys: ["promet", "nesrece"],
		collection: accidentsCollection,
		attribute: "PRSP_Promet",
		regex: false
	},
	graph32: {
		id: 32,
		title: "Nesreče glede na tipe cest",
		values: [
			"0",
			"1",
			"2",
			"3",
			"4",
			"5",
			"A",
			"H",
			"L",
			"M",
			"N",
			"R",
			"T",
			"V",
			"0",
			"1",
			"2",
			"3",
			"4",
			"5",
			"H",
			"L",
			"N",
			"T",
			"V"
		],
		decodedValues: [
			"AVTOCESTA",
			"GLAVNA CESTA",
			"GLAVNA CESTA",
			"REGIONALNA CESTA",
			"REGIONALNA CESTA",
			"REGIONALNA CESTA",
			"AVTOCESTA - STARA",
			"HITRA CESTA",
			"LOKALNA CESTA",
			"MAGISTRALNA CESTA - STARA",
			"NASELJE Z ULIČNIM SISTEMOM",
			"REGIONALNA CESTA - STARA",
			"TURISTIČNA CESTA",
			"NASELJE BREZ ULIČNEGA SISTEMA",
			"AC",
			"G1",
			"G2",
			"R1",
			"R2",
			"R3",
			"HC",
			"XC",
			"MESTO",
			"RT",
			"VAS"
		],
		keys: ["cesta", "nesrece"],
		collection: accidentsCollection,
		attribute: "LOVC_vrsta_ceste",
		regex: false
	},
	graph33: {
		id: 33,
		title: "Nesrece glede na spol",
		values: ["M", "Z"],
		decodedValues: ["MOSKI", "ZENSKA"],
		keys: ["spol", "nesrece"],
		collection: peopleCollection,
		attribute: "spol",
		regex: false
	}
};
